[package]
name = "ddd-rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rd"
path = "src/main.rs"

[[bin]]
name = "ddd_rust"
path = "src/bin/ddd_rust.rs"

[[bin]]
name = "ddd_rust_sample_api"
path = "src/bin/sample_api.rs"

[dependencies]
axum = { version = "0.8", features = ["macros", "json"] }
tokio = { version = "1.0", features = ["full"] }
hyper = { version = "1.0", features = ["full"] }
config = { version = "0.15", features = ["toml"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = ["mysql", "runtime-tokio-native-tls", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2.0"
anyhow = "1.0"
futures = "0.3"
tokio-util = { version = "0.7", features = ["full"] }
crossbeam-channel = "0.5"
crossbeam = "0.8"
rand = "0.9"
